---
# This workflow will install dependencies and run tests

name: Rust Checks

on:
  push:
    branches:
      - main
    paths-ignore:
      # Ignore .md files, COPYING, and CONTRIBUTING anywhere in the repo.
      # Ignore files in the .github/img folder
      - '**.md'
      - '**/COPYING'
      - '**/CONTRIBUTING'
      - '.github/img/*'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: rustfmt
        run: rustfmt --check src/*.rs

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Test
        run: |
          cargo check
          cargo test
